# Generated by Django 2.0.3 on 2020-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
