# Generated by Django 2.0.3 on 2020-07-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_element_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='app_name',
            new_name='app_id',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='page_name',
            new_name='page_id',
        ),
    ]
